### PR TITLE
Update json files sumodule.

### PR DESCRIPTION
**Pull request by bcremer**
Compare: https://github.com/Haehnchen/idea-php-toolbox-json-files/compare/03d080ab5c34d046a3de46570a2d8f1deac95344...5864f5b9cf9d0e8425ee241b5fc8329d0d8eadd5

### CODE REVIEW

**Comment by Koc** [comment]
@Haehnchen is it possible automatically update json files?

**Comment by Haehnchen** [comment]
@Koc i was thinking about a http update method. lets see ;)

**Comment by Koc** [comment]
like download https://github.com/Haehnchen/idea-php-toolbox-json-files/archive/master.zip from PHPStorm?

**Comment by Haehnchen** [comment]
@bcremer new files shipped with `0.4.1`
@Koc users need a more specialized download and activation flag. eg many signatures handled by their own plugins.

**Comment by bcremer** [comment]
Is there a benefit in keeping the json files in an separate repository at all?

**Comment by Haehnchen** [comment]
yes, the mentioned download workflow. :) i want to decouple it from a plugin release and provide some IDE notifications for updated files somehow.

**Pull request merged**
